-- CRIANDO TABELA PERFIL
CREATE TABLE PERFIL (
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DESCRICAO VARCHAR(40) DEFAULT NULL
) ;
-- INSERINDO DADOS INICIAIS NA TABELA PERFIL
INSERT INTO PERFIL (ID, DESCRICAO) VALUES
(1, 'ADMINISTRADOR'),
(2, 'USUARIO');
-- CRIANDO TABELA USUARIO
CREATE TABLE USUARIO (
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(255) DEFAULT NULL,
  USUARIO VARCHAR(60) DEFAULT NULL,
  SENHA VARCHAR(100) DEFAULT NULL,
  PERFIL INT(11) DEFAULT NULL,
  EMAIL VARCHAR(80) DEFAULT NULL,
  IMAGEM VARCHAR(100) DEFAULT NULL,
  ATIVO ENUM('0','1') DEFAULT NULL
);

INSERT INTO APPLOGIN.USUARIO 
VALUES (0,'Master','master','$2y$10$90hd/OkyEeKaIssAtk.AeOkUDCx2ziHivkJ4CTC7XyGqmh46n..vS','0','master@master.com','6803f5c19b487_calca-masculina.jpg','1')
